// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZhiDaCore.EFCore;

namespace ZhiDaCore.EFCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181203054018_Initial1203")]
    partial class Initial1203
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZhiDaCore.Entity.Trades.Trade", b =>
                {
                    b.Property<int>("SequenceID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNo");

                    b.Property<string>("AccountType");

                    b.Property<DateTime?>("BizDate");

                    b.Property<string>("BizUnit");

                    b.Property<string>("BusinessDate");

                    b.Property<string>("Ccy");

                    b.Property<string>("ClearingMember");

                    b.Property<int>("ContractSize");

                    b.Property<string>("EventDesc");

                    b.Property<string>("EventType");

                    b.Property<string>("Exchange");

                    b.Property<string>("GroupId");

                    b.Property<DateTime?>("InsertDate");

                    b.Property<string>("MMY");

                    b.Property<string>("Market");

                    b.Property<string>("Multiplier");

                    b.Property<string>("ProductCode");

                    b.Property<string>("PutCall");

                    b.Property<int>("Qty");

                    b.Property<string>("SecType");

                    b.Property<string>("Side");

                    b.Property<string>("StrikePrice");

                    b.Property<decimal?>("StrikePx");

                    b.Property<DateTime>("TradeDate");

                    b.Property<string>("TradeId");

                    b.Property<decimal?>("TradePrice");

                    b.Property<string>("TradingMember");

                    b.Property<string>("TradingUser");

                    b.Property<DateTime?>("TransTime");

                    b.HasKey("SequenceID");

                    b.ToTable("Trade");
                });

            modelBuilder.Entity("ZhiDaCore.Entity.Trades.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime>("ModityTime");

                    b.Property<string>("Password");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
